### ISSUE TITLE
XState Inspect waiting for connection

### ISSUE THREAD

**Issue by theClarkSell** [distolma/xstate-svelte#36] opened 2020-10-22 13:41 UTC
@distolma first wonderful package and thank you for the hard work. It's been great to work with. 

Right now this is more of a question than anything else. Have you tried getting inspect to work? https://xstate.js.org/docs/packages/xstate-inspect/

I tried adding it to my project but it just says waiting for connection. https://github.com/ThatConference/that.us/pull/421

After trying to debug the magic I forked this off and tried bumping the XState packages as it seems it might have come out after your initial release, but for some reason when I `npm link` things to test, something is going on and it's not working. 

My other thought might be how the options and the machine config are merged to kick off debugging but I haven't looked that close at your code.

Rambling aside:
* have you tried inspect yet with your package?
* yes i need to try a much smaller project and work up. I'll try to get something in codesandbox later today.
* do you have any contribution / build docs? like I said I tried to fork thing, but I think I might have either the build process or the linking wrong. 

Thank you for the awesome package!
~ Clark

**Comment by distolma** [comment] 2020-10-22 14:01
Hello @csell5 

Thank you for your interest in this project.
I've been trying to reproduce your case, and it's supposed to work ([link](https://codesandbox.io/s/stoic-field-qh8o3)).
Maybe one of the reasons your case isn't working is a missed `devTools: true` flag.
If this example doesn't help you, please modify my example or send me a link of your example.

**Comment by theClarkSell** [comment] 2020-10-22 15:07
Interesting and good news. I forked yours and just pulled it up to more of what I had locally.. It still works in CodeSandbox but if I pull it down locally and try to run it I get the following error.

`
rollup v2.32.1
bundles main.js → public/build/bundle.js...
LiveReload enabled
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@xstate/inspect/es/index.js
1: var __assign = (this && this.__assign) || function () {
                   ^
2:     __assign = Object.assign || function(t) {
3:         for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 1 other occurrence
created public/build/bundle.js in 1s
`
So there is something about rollup that seems to be affecting things between the two. Are you seeing the same?

My fork of your sandbox - https://codesandbox.io/s/xstate-inspect-fork-n4c92?file=/rollup.config.js

**Comment by distolma** [comment] 2020-10-22 15:42
@csell5 thanks for your example.
I was able to reproduce the problem, and I think I know the solution.
Fix will be in the nearest future.

**Comment by theClarkSell** [comment] 2020-10-22 15:44
That's awesome cause I'm a bit lost. I think I get what's all going on but a little lost after that.

**Comment by distolma** [comment] 2020-10-22 15:50
You are right, this problem caused by a Rollup, it automatically changes global `this` to `undefined`, and this is breaks `__assign` and `__rest` functions generated by Typescript.

**Comment by distolma** [comment] 2020-10-23 09:15
Just released 1.0.1 with this change in it.

**Comment by distolma** [comment] 2020-10-23 09:18
@csell5  But this error still reproduces with other modules (e.g. `@xstate/inspect`). So [this](https://stackoverflow.com/a/43556986/10691507) is a workaround.

Returning to our original promblem, I supose that it is not `xstate-svelte` a problem. Probably this `@xstate/inspect` is a issue (or feature), this inspector working good with `codesandbox` (maybe sandbox is on internet), and doesn't work with a local project (maybe `https://statecharts.io/inspect` cannot connect to your local server).

So this question is relevant to [`@xstate`](https://github.com/davidkpiano/xstate) project rather than to this.

**Comment by theClarkSell** [comment] 2020-10-23 14:03
@distolma I just wanted to say thank you again for jumping on this with me. As you can see I logged an issue over in XState and referenced it back here. 

Keep up the awesome stuff!

**Comment by theClarkSell** [comment] 2020-10-23 14:04
> So [this](https://stackoverflow.com/a/43556986/10691507) is a workaround.

Also I did see this too, I just wasn't sure what I should be setting the context too and if that just did it globally.

**Closed as completed** 2020-11-01 09:54 UTC
